# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Barker Progressive
slogan: Big enough to Serve, Small enough to Care
email: sales@barkerprogressive.com
description: Barker Progressive Group has been providing businesss and financial services to the people of Bolivar for 35 years.
owner: Kodi Poindexter
phone: +1 417 326 3140
fax: +1 417 326 8172
address: PO Box 1842, Nixa, Missouri 65714
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://barkerprogressive.com" # the base hostname & protocol for your site,


# Build settings
markdown: kramdown
